server/mainapp/urls.py
from django.urls import path

from .views import (
    main, support
)

app_name = 'mainapp'

urlpatterns = [
    path('', main, name='main'),
    path('support/', support, name='support')
]

server/productsapp/urls.py
from django.urls import path

from .views import (
    product_detail, product_list
)

app_name = 'productsapp'

urlpatterns = [
    path('<int:pk>', product_list, name='main'),
    path('detail/', product_detail, name='detail')
]

server/server/urls.py
from django.contrib import admin
from django.conf.urls.static import static
from django.urls import path, include
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('products/', include('productsapp.urls')),
    path('', include('mainapp.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

server/mainapp/models.py
from django.db import models

# Create your models here.

server/productsapp/models.py
from django.db import models

# Create your models here.

class Category(models.Model):
    name = models.CharField(
        max_length = 255,
        blank = True,
        null = True, 
        default = 'empty', 
        )

    def __str__(self):
        return self.name


class Type(models.Model):
    name = models.CharField(
        max_length = 255,
        blank = True,
        null = True,
        )

    category = models.ForeignKey(
        Category,
        on_delete=models.CASCADE,
        )

    def __str__(self):
        return self.name   


class ProductPhoto(models.Model):

    image = models.ImageField(
        upload_to = 'products',
        null = True,
        blank = True,
    ) 

    description = models.TextField(
        blank = True,
        null = False,
    )

    def __str__(self):
        return self.description


class Colour(models.Model):

    name = models.CharField(
        max_length = 255,
        blank = True,
        null = True,
    )

    def __str__(self):
        return self.name

class Diagonal(models.Model):

    name = models.CharField(
        max_length = 255,
        blank = True,
        null = True,
    )

    def __str__(self):
        return self.name

class Memory(models.Model):

    name = models.CharField(
        max_length = 255,
        blank = True,
        null = True,
    )

    def __str__(self):
        return self.name

class Processor(models.Model):

    name = models.TextField(
        blank = True,
        null = True,
    )

    def __str__(self):
        return self.name


class Features(models.Model):

    name = models.CharField(
        max_length = 255,
        blank = True,
        null = True,
    )

    def __str__(self):
        return self.name


class Storage(models.Model):

    name = models.CharField(
        max_length = 255,
        blank = True,
        null = True,
    )

    def __str__(self):
        return self.name


class Band(models.Model):

    name = models.CharField(
        max_length = 255,
        blank = True,
        null = True,
    )

    def __str__(self):
        return self.name


class CaseMaterial(models.Model):

    name = models.CharField(
        max_length = 255,
        blank = True,
        null = True,
    )

    def __str__(self):
        return self.name


class Connectivity(models.Model):

    name = models.CharField(
        max_length = 255,
        blank = True,
        null = True,
    )

    def __str__(self):
        return self.name


class Year(models.Model):

    name = models.CharField(
        max_length = 255,
        blank = True,
        null = True,
    )

    def __str__(self):
        return self.name


class Description(models.Model):

    name = models.TextField(
        blank = True,
        null = True,
    )

    def __str__(self):
        return self.name


class Product(models.Model):

    name = models.CharField(
        max_length = 255,
        blank = True,
        null = True,
    )

    short_description = models.CharField(
        max_length = 255,
        blank = True,
        null = True,
    )

    category = models.ForeignKey(
        Category,
        on_delete = models.CASCADE,
    )

    type = models.ForeignKey(
        Type,
        on_delete = models.CASCADE,
    )

    productphoto = models.ForeignKey(
        ProductPhoto,
        on_delete = models.SET_NULL,
        null = True,
        blank = True,
    )

    colour = models.ForeignKey(
        Colour,
        on_delete = models.SET_NULL,
        null = True,
        blank = True,
    )

    diagonal = models.ForeignKey(
        Diagonal,
        on_delete = models.SET_NULL,
        null = True,
        blank = True,
    )

    memory = models.ForeignKey(
        Memory,
        on_delete = models.SET_NULL,
        null = True,
        blank = True,
    )

    processor = models.ForeignKey(
        Processor,
        on_delete = models.SET_NULL,
        null = True,
        blank = True,
    )

    features = models.ForeignKey(
        Features,
        on_delete = models.SET_NULL,
        null = True,
        blank = True,
    )

    storage = models.ForeignKey(
        Storage,
        on_delete = models.SET_NULL,
        null = True,
        blank = True,
    )

    band = models.ForeignKey(
        Band,
        on_delete = models.SET_NULL,
        null = True,
        blank = True,
    )

    casematerial = models.ForeignKey(
        CaseMaterial,
        on_delete = models.SET_NULL,
        null = True,
        blank = True,
    )

    connectivity = models.ForeignKey(
        Connectivity,
        on_delete = models.SET_NULL,
        null = True,
        blank = True,
    )

    year = models.ForeignKey(
        Year,
        on_delete = models.SET_NULL,
        null = True,
        blank = True,
    )

    description = models.ForeignKey(
        Description,
        on_delete = models.SET_NULL,
        null = True,
        blank = True,
    )

    price = models.DecimalField(
        max_digits = 12,
        decimal_places = 2,
        default = 0,
        )

    discount = models.DecimalField(
        max_digits = 2,
        decimal_places = 2,
        default = 0,
        null = True,
    )

    created = models.DateTimeField(
        auto_now_add = True,
    )

    modified = models.DateTimeField(
        auto_now = True,
    )

    def __str__(self):
        return f'{self.name} {self.short_description}' 

server/mainapp/views.py
from django.shortcuts import render
from productsapp.models import Category, Type, Product

# Create your views here.

def main(requiest):
    return render(
        requiest,
        'mainapp/index.html',
        {
            'args' : [
                {'src': '/static/mainapp/media/ipad-pro-12in-cell-select-gold.jpg', 'name': 'Apple iPad Pro 12.9"(2017)', 'description': '512GB Wi-Fi + Cellular Gold', 'old_price': '91.990₽', 'new_price': '86.990₽'},
                {'src': '/static/mainapp/media/ipad-wifi-select-gold-201803.212x212.png', 'name': 'Apple iPad (2018)', 'description': '128GB Wi-Fi + Cellular Gold', 'old_price': '42.490₽', 'new_price': '39.490₽'},
                {'src': '/static/mainapp/media/iphone7-rosegold-select-2016_av1.212x212.png', 'name': 'Apple iPhone 7', 'description': '32GB Rose Gold', 'old_price': '34.990₽', 'new_price': '31.990₽'},
                {'src': '/static/mainapp/media/mnng2ru.212x212.jpeg', 'name': 'Apple Watch Series 2', 'description': '38mm, silver, алюминевые', 'old_price': '91.990₽', 'new_price': '86.990₽'},
                {'src': '/static/mainapp/media/MacBookAirSale.jpg', 'name': 'MacBook Air 13'' (2017)', 'description': '1.8Ghz, 8Gb, 128Gb (РСТ)', 'old_price': '71.990₽', 'new_price': '61.990₽'},
                {'src': '/static/mainapp/media/tv4.png', 'name': 'Apple TV 4'' (2017)', 'description': '32Gb', 'old_price': '13.990₽', 'new_price': '10.990₽'},
                {'src': '/static/mainapp/media/beats_one.jpeg', 'name': 'Беспроводные наушники', 'description': 'Beats x', 'old_price': '8.990₽', 'new_price': '7.490₽'},
                {'src': '/static/mainapp/media/beats_two.jpeg', 'name': 'Наушники Beats', 'description': 'Solo3 Wireless', 'old_price': '71.990₽', 'new_price': '61.990₽'}
            ]
        }
        )

def support(requiest):
    return render(requiest, 'mainapp/support.html')

server/productsapp/views.py
from django.shortcuts import render
from .models import Category, Type, Product

# Create your views here.

def product_list(requiest, pk):
    return render(
        requiest, 
        'productsapp/product_list.html',
        {
            'categorys' : Category.objects.all(), 
            'types' : Type.objects.all(),
            'product' : Product.objects.all(),
        }
    )

def product_detail(requiest):
    return render(requiest, 'productsapp/product_detail.html')

server/mainapp/templates/mainapp/index.html
{% extends 'server/master.html' %}

{% block page_tittle %}
Job'Store
{% endblock %}

{% block page_content %}
        <main class="main">

            <div class="sales">
                <div class="main_header">Февральские акции</div>

                <div class="sales_content">

                    {% for itm in args %}
                    <div class="product_vision_one">
                            <img class="img_vision_one" src="{{ itm.src }}" alt="{{ itm.name }}">
                            <div class="name_vision_one">
                                    {{ itm.name }}
                            </div>
                            <div class="name_vision_one">
                                    {{ itm.description }}
                            </div>
                            <div class="price">
                                <div class="old_price">{{ itm.old_price }}</div>
                                <div class="new_price">{{ itm.new_price }}</div>
                            </div>
    
                            <button class="buy_button">
                                В корзину
                            </button>
                        </div>
                    {% endfor %}

                </div>
            </div>



        </main>
{% endblock %} 

server/mainapp/templates/mainapp/support.html
{% extends 'server/master.html' %}

{% block page_tittle %}
Support
{% endblock %}

{% block page_content %}
<main class="main">
    <div class="main_header">Поддержка</div>

    <div class="support">
        <div class="wrapper_support">
        </div>
    </div>

    <form class="user_form">
        <div class="data">
            <div class="personal_data">
                <input class="user_form_personal_data" type="text" placeholder="имя" size="32" height="15">
                <input class="user_form_personal_data" type="text" placeholder="почта" size="32">
                <input class="user_form_personal_data" type="text" placeholder="тема/устройство" size="32">
            </div>
            <div class="textarea_data">
                <textarea class="user_form_area" type="text" cols='30' rows="10" placeholder="Ваше сообщение"></textarea>
            </div>
        </div>
        <button class="send_button">Отправить</button>
    </form>

    <div class="main_header map_name">Наш адрес</div>
    
    <div class="adress">г.Москва, Новинский бульвар, дом 8</div>

    <div class="map_script">
        <script type="text/javascript" charset="utf-8" async src="https://api-maps.yandex.ru/services/constructor/1.0/js/?um=constructor%3A4cbd5591d5aa58cba99fbed1906fb4d7f9b11f70aac4137d35e2cd4b1a35ac5f&amp;width=1160&amp;height=450&amp;lang=ru_RU&amp;scroll=true"></script>
    </div>


</main>
{% endblock %}

server/productsapp/templates/productsapp/product_detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Document</title>
    <link rel="stylesheet" href="/static/mainapp/css/css.css">
</head>
<body>
    <h1>
        This is product detail
    </h1>
</body>
</html>

server/productsapp/templates/productsapp/product_list.html
{% extends 'server/master.html' %}

{% block page_tittle %}
{{ Category.name }}
{% endblock %}

{% block page_content %}
        <main class="main">

            <div class="sales">
                <div class="main_header">{{ Category.name }}</div>

                <div class="sales_content">

                    {% for itm in types %}
                    <div class="product_vision_one">
                            <img class="img_vision_one" src="{{ itm.src }}" alt="{{ itm.name }}">
                            <div class="name_vision_one">
                                    {{ type.name }}
                            </div>
                            <div class="name_vision_one">
                                    {{ product.description }}
                            </div>
                            <div class="price">
                                <div class="old_price">{{ product.old_price }}</div>
                                <div class="new_price">{{ product.new_price }}</div>
                            </div>
    
                            <button class="buy_button">
                                В корзину
                            </button>
                        </div>
                    {% endfor %}

                </div>
            </div>



        </main>
{% endblock %} 

server/server/templates/server/master.html
{% load static %}

<!DOCTYPE html>
<html lang="ru">

<head>
    <meta charset="UTF-8">
    <title>
        {% block page_tittle %}{% endblock %}
    </title>
    <link rel="stylesheet" href="{% static 'mainapp/css/css.css' %}">
</head>

<body class="body">

    <header class="header">

        <div class="header_presentation">
            <div class="brand">
                <a href="{% url 'mainapp:main' %}" class="main_page">
                    <div class="brand_name">Job'Store</div>
                    <div class="brand_description">Магазин техники Apple</div>
                </a>
            </div>

            <div class="open">
                <img src="/static/mainapp/media/open_sign.png" alt="" class="open_sign">
                <div class="open_time">с 10:00 до 21:00</div>
            </div>

            <div class="contacts">
                <div class="contacts_name">
                    <div class="phone_number_name">phone number:</div>
                    <div class="email_name">email:</div>
                    <div class="telegram_name">telegram:</div>
                </div>
                <div class="contacts_data">
                    <div class="phone_number">+7 (495) 555 77 55</div>
                    <div class="email">hello@jobstore.ru</div>
                    <div class="telegram">@jobstore</div>
                </div>
            </div>
        </div>
    </header>

    <div class="menu_panel">
        <ul class="navigation_menu">

            {% for itm in categorys %}
            <li class="menu_li"><a class="menu_a" href="{% url 'productsapp:main' pk=itm.id %}">{{ categorys.name }}</a>
                <div class="wrapper_secondfloor">
                    <ul class="navigation_menu_secondfloor">
                        {% for i in types %}
                            {% if itm.id == types.category  %}
                                <li class="menu_secondfloor"><a href="" class="a_secondfloor">{{ types.name }}</a></li>
                            {% endif %}
                        {% endfor %}
                    </ul>
                </div>
            </li>
            {% endfor %}

            <li class="menu_li"><a class="menu_a" href="mac.html">Mac</a>
                <div class="wrapper_secondfloor">
                    <ul class="navigation_menu_secondfloor">
                        <li class="menu_secondfloor"><a href="" class="a_secondfloor">iMac</a></li>
                        <li class="menu_secondfloor"><a href="" class="a_secondfloor">MacBook Pro</a></li>
                        <li class="menu_secondfloor"><a href="" class="a_secondfloor">MacBook Air</a></li>
                        <li class="menu_secondfloor"><a href="" class="a_secondfloor">MacBook</a></li>
                        <li class="menu_secondfloor"><a href="" class="a_secondfloor">Mac Pro</a></li>
                        <li class="menu_secondfloor"><a href="" class="a_secondfloor">Mac Mini</a></li>
                    </ul>
                </div>
            </li>
            <li class="menu_li"><a class="menu_a" href="iphone.html">iPhone</a>
                <div class="wrapper_secondfloor">
                    <ul class="navigation_menu_secondfloor">
                        <li class="menu_secondfloor"><a href="" class="a_secondfloor">iPhone 6</a></li>
                        <li class="menu_secondfloor"><a href="" class="a_secondfloor">iPhone 6s</a></li>
                        <li class="menu_secondfloor"><a href="" class="a_secondfloor">iPhone 7</a></li>
                        <li class="menu_secondfloor"><a href="" class="a_secondfloor">iPhone 8</a></li>
                        <li class="menu_secondfloor"><a href="" class="a_secondfloor">iPhone X</a></li>
                        <li class="menu_secondfloor"><a href="" class="a_secondfloor">iPhone Xs</a></li>
                    </ul>
                </div>
            </li>
            <li class="menu_li"><a class="menu_a" href="watch.html">Watch</a>
                <div class="wrapper_secondfloor">
                    <ul class="navigation_menu_secondfloor">
                        <li class="menu_secondfloor"><a href="" class="a_secondfloor">Watch Series 4</a></li>
                        <li class="menu_secondfloor"><a href="" class="a_secondfloor">Watch 4 Nike+</a></li>
                        <li class="menu_secondfloor"><a href="" class="a_secondfloor">Watch Series 3</a></li>
                        <li class="menu_secondfloor"><a href="" class="a_secondfloor">Watch 3 Nike+</a></li>
                        <li class="menu_secondfloor"><a href="" class="a_secondfloor">Watch Series 2</a></li>
                        <li class="menu_secondfloor"><a href="" class="a_secondfloor">Watch 2 Nike+</a></li>
                    </ul>
                </div>
            </li>
            <li class="menu_li"><a class="menu_a" href="watch.html">iPad</a>
                <div class="wrapper_secondfloor">
                    <ul class="navigation_menu_secondfloor">
                        <li class="menu_secondfloor"><a href="" class="a_secondfloor">iPad Pro 12.9</a></li>
                        <li class="menu_secondfloor"><a href="" class="a_secondfloor">iPad Pro 11</a></li>
                        <li class="menu_secondfloor"><a href="" class="a_secondfloor">iPad Pro 10.5</a></li>
                        <li class="menu_secondfloor"><a href="" class="a_secondfloor">iPad 2018</a></li>
                        <li class="menu_secondfloor"><a href="" class="a_secondfloor">iPad 2017</a></li>
                        <li class="menu_secondfloor"><a href="" class="a_secondfloor">iPad Mini</a></li>
                    </ul>
                </div>
            </li>
            <li class="menu_li"><a class="menu_a" href="watch.html">TV</a>
                <div class="wrapper_secondfloor">
                    <ul class="navigation_menu_secondfloor">
                        <li class="menu_secondfloor"><a href="" class="a_secondfloor">Apple TV 4K</a></li>
                        <li class="menu_secondfloor"><a href="" class="a_secondfloor">Apple TV 4</a></li>
                        <li class="menu_secondfloor"><a href="" class="a_secondfloor">Apple HomePod</a></li>
                    </ul>
                </div>
            </li>
            <li class="menu_li"><a class="menu_a" href="{% url 'mainapp:support' %}">Поддержка</a></li>
            <li class="menu_li"><a class="menu_a_graphic" href="cart.html"><img class="icon_link" src="/static/mainapp/media/icons8-shopping_bag.png" alt="cart"></a></li>
            <li class="menu_li"><a class="menu_a_graphic" href="search.html"><img class="icon_link" src="/static/mainapp/media/icons8-search.png" alt="search"></a></li>
        </ul>

    </div>

    <div class="wrapper">
        {% block page_content %}{% endblock %}
    </div>

    <footer class="footer">
        <div class="copy">&copy; Все права защищены у Алексея Кадочникова</div>
    </footer>

</body>

</html>